# -*- coding: utf-8 -*-
"""OSHA C_Site_safety with CV .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oMobfNBIKkiTSnMGBCdhUV70dfOhNFyC
"""

!pip install ultralytics

import os

from ultralytics import YOLO
import cv2
import matplotlib.pyplot as plt

!pip install roboflow
from roboflow import Roboflow

rf = Roboflow(api_key="um0P69wucTNGPhrNfSil")
project = rf.workspace("roboflow-universe-projects").project("construction-site-safety")
dataset = project.version(1).download("yolov8")

import os

dataset_path = dataset.location

print("Dataset path:", dataset_path)
print("\nContents:")
for item in os.listdir(dataset_path):
    print(item)

with open(os.path.join(dataset_path, "data.yaml"), "r") as f:
    print(f.read())

model = YOLO("yolov8n.pt")

model.train(
    data=os.path.join(dataset_path, "data.yaml"),
    epochs=50,
    imgsz=640,
    batch=16,
    project="industry_safety",
    name="yolov8n_baseline"
)

metrics = model.val()
print(metrics)

results = model.predict(
    source=os.path.join(dataset_path, "test/images"),
    conf=0.25,
    save=True
)

from IPython.display import Image, display
import glob

pred_path = "/content/industry_safety/yolov8n_baseline/predict"

images = glob.glob(f"{pred_path}/*.jpg")[:5]

for img in images:
    display(Image(filename=img))

model.predict(
    source="/content/images.jpeg",
    conf=0.3,
    save=True
)

for r in results[:5]:
    img = r.plot()
    plt.figure(figsize=(8, 6))
    plt.imshow(img)
    plt.show()

model = YOLO("/content/industry_safety/yolov8n_baseline2/weights/best.pt")

# Path to validation images
val_images_path = os.path.join(dataset_path, "valid/images")
images = [os.path.join(val_images_path, img) for img in os.listdir(val_images_path)]

violation_count = 0

for img_path in images:
    results = model(img_path)[0]  # get predictions for one image
    for box in results.boxes:
        cls_id = int(box.cls[0])
        conf = float(box.conf[0])
        label = model.names[cls_id]
        if conf >= 0.75 and label.startswith("NO-"):
            violation_count += 1
            break  # count each image only once
print(f"Images with OSHA violations (≥75% confidence): {violation_count} / {len(images)}")

"""Total images checked: 57

Images flagged for high-confidence OSHA violations: 2

Detection threshold: 75% confidence
"""

!pip install mlflow

import mlflow
import mlflow.pytorch

mlflow.set_experiment("OSHA_Safety_Detection")

with mlflow.start_run():
    mlflow.log_param("model", "YOLOv8n")
    mlflow.log_param("confidence_threshold", 0.75)
    mlflow.log_param("epochs", 50)

    mlflow.log_metric("violation_images", 2)
    mlflow.log_metric("total_images", 57)

    mlflow.pytorch.log_model(model.model, "yolo_model")

DATASET_VERSION = "v1.0-roboflow"

mlflow.log_param("dataset_version", DATASET_VERSION)

DATASET_VERSION = "v2.0-manual-labels"

def evaluate_osha_violations(model, image_paths, threshold=0.75):
    violation_images = []

    for img in image_paths:
        results = model(img)[0]
        for box in results.boxes:
            label = model.names[int(box.cls[0])]
            conf = float(box.conf[0])
            if conf >= threshold and label.startswith("NO-"):
                violation_images.append(img)
                break

    return violation_images

violations = evaluate_osha_violations(model, images, 0.75)
print(f"{len(violations)} / {len(images)} images violate OSHA")

import shutil
import os

os.makedirs("osha_violations", exist_ok=True)

for img in violations:
    shutil.copy(img, "osha_violations/")

mlflow.log_artifacts("osha_violations")

for t in [0.5, 0.6, 0.75, 0.9]:
    violations = evaluate_osha_violations(model, images, t)
    mlflow.log_metric(f"violations_at_{int(t*100)}", len(violations))

!pip install streamlit ultralytics pillow opencv-python cloudflared

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import streamlit as st
# from ultralytics import YOLO
# from PIL import Image
# import tempfile
# 
# st.set_page_config(page_title="OSHA Safety Detector", layout="centered")
# 
# st.title("🚧 OSHA Construction Site Safety Detector")
# st.write("Detect safety violations (NO-Hardhat) using YOLOv8")
# 
# @st.cache_resource
# def load_model():
#     return YOLO("best.pt")  # upload your trained model
# 
# model = load_model()
# 
# conf_thres = st.slider("Confidence Threshold", 0.1, 1.0, 0.75)
# 
# uploaded = st.file_uploader("Upload an image", type=["jpg", "png", "jpeg"])
# 
# if uploaded:
#     img = Image.open(uploaded)
#     st.image(img, caption="Uploaded Image", use_container_width=True)
# 
#     with tempfile.NamedTemporaryFile(delete=False, suffix=".jpg") as tmp:
#         img.save(tmp.name)
#         results = model(tmp.name, conf=conf_thres)[0]
# 
#     violation = False
#     for box in results.boxes:
#         label = model.names[int(box.cls[0])]
#         if label.startswith("NO-"):
#             violation = True
# 
#     if violation:
#         st.error("⚠️ OSHA SAFETY VIOLATION DETECTED")
#     else:
#         st.success("✅ No OSHA violation detected")
# 
#     st.image(results.plot(), caption="Detection Result", use_container_width=True)

# Download the latest cloudflared binary for Linux
!wget -q https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64

# Make it executable
!chmod +x cloudflared-linux-amd64

# Move it to /usr/local/bin so you can call it as 'cloudflared'
!mv cloudflared-linux-amd64 /usr/local/bin/cloudflared

# Check version to confirm installation
!cloudflared --version

!cloudflared tunnel --url http://localhost:8501

!pip install cloudflared
!python3 -m cloudflared tunnel --url http://localhost:8501

!streamlit run app.py & npx cloudflared tunnel --url http://localhost:8501